### ISSUE TITLE
USB device not found

### ISSUE THREAD

**Issue by procrash** [maxieds/ChameleonMiniLiveDebugger#16]
Hi,

I have a OnePlus 3+ and the USB Device is not found if I connect the chameleon mini to my android phone. Is there anything I need to consider to get the app to work?

Cheers,

Wolfgang

**Comment by maxieds** [comment]
Try disconnecting the device and closing the app. Then reconnect the
device. It should bring up a list of programs and this app should be one of
them. Does your phone have usbc? If not, some older devices will not power
external USB devices, so it could be an issue with your phone as well. Let
me know if this works for you.

**Comment by maxieds** [comment]
This has been a while since there have been updates. Closing issue as not relevant any more.
