### ISSUE TITLE
Supported Boards

### ISSUE THREAD

**Issue by AndreasBujok** [maxieds/ChameleonMiniLiveDebugger#18]
Hi,

does it also complete work with RevG Boards?

Thanks

**Comment by AndreasBujok** [comment]
Sorry, my fault. I used a actual RevG Board but the most functions don't work.
I'm using an Samsung A5.

Thanks

**Comment by maxieds** [comment]
There are a couple of things that come to mind: Does your phone have usb-c?
Is the app showing that it recognizes the board? Please post a screenshot
of the running app, and more details of what you tried so I can help you to
debug.

**Comment by maxieds** [comment]
This has been a while since there have been updates. Closing issue as not relevant any more.
