### ISSUE TITLE
Unconfigured red button(power on) it can’t power on

### ISSUE THREAD

**Issue by FFcafe1** [maxieds/ChameleonMiniLiveDebugger#19]
Hi everyone. I recently bought chameleon mini rev E on aliexpress. 
Before that I installed this apk, (v: 0.5.3-free) I could power on with the red button, but after i installed and i modified the buttons with this configuration:
Red led: powered
Green led: ledgren
RBS: rbutton 
Rbl: rbutton_long
Lbs: lbutton
Lbl: uid_right_decr
REVE: switchcard 
Log: memory
—-
I upload this configuration and right now I can’t power on my chameleon, I push power on button and It power on, but when I don’t push the button it shut down.
Some help?

**Comment by maxieds** [comment]
This has been a while since there have been updates. Closing issue as not relevant any more.
