### ISSUE TITLE
New Feature Requests

### ISSUE THREAD

**Issue by maxieds** [maxieds/ChameleonMiniLiveDebugger#2]
Here are some features I want to add:

- ~~Better APDU command recognition~~ (To a certain extent)
- ~~Ability to download a log binary file from the device (LOGDOWNLOAD) using a XModem connection and display it as though it were a live log~~
- ~~Query the device for its current settings of the peripherals (_working on this now_)~~
- Search functionality (byte strings and ascii)
- Compute entropy of a frame (i.e., should it be a command, or more likely encrypted data?)
- ~~fix the blank tabs bug when it reloads on USB intent / device gets plugged in~~
- ~~Export DUMP_MFU to binary file (TODO later)~~
- ~~Upload a new card profile with XModem~~

**Comment by maxieds** [comment]
# Add Detailed JavaDocs (This is important)

... And will get done eventually. It's just my least favorite part of the software engineering scheme of things. To much other cool stuff to implement and get working first.

**Comment by maxieds** [comment]
The primary "mainstream" (i.e., built-in to the Chameleon Mini command line) feature that still needs to be added at this point is the uploading of card data via XModem.

**Comment by jankais3r** [comment]
It would be awesome to have a "1-button-cloning" in the app. Something similar to [this](https://github.com/emsec/ChameleonMini/pull/103/commits/efe1c5d89924f90a997700b8ee8d80096164dc0f).

**Comment by maxieds** [comment]
I just barely skimmed the source code you linked (I'm super busy today!). So what you want is a 1-button way to clone an external tag to the Chameleon Mini, is that correct?
