### ISSUE TITLE
Crash Report: CMLD 1.2.9-free running samsung/beyond2qltesq/beyond2q:10/QP1A.190711.020/G975USQU4ETH7:user/release-keys G975USQS4ETJ2 [SDK 29] on device samsung beyond2qltesq SM-G975U

### ISSUE THREAD

**Issue by SHMAUS-Carter** [maxieds/ChameleonMiniLiveDebugger#31]
@maxieds:

**Crash data summary:**
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
* *[Ljava.lang.String;@313e85*: [Ljava.lang.String;@5e254da
**Stack trace:**
" + "```java
Could not execute method for android:onClick

L01| androidx.appcompat.app.h$a.
     onClick( AppCompatViewInflater.java:4 )
L02| android.view.View.
     performClick( View.java:7862 )
L03| android.widget.TextView.
     performClick( TextView.java:15004 )
L04| android.view.View.
     performClickInternal( View.java:7831 )
L05| android.view.View.access$3600( View.java:879 )
L06| android.view.View$PerformClick.
     run( View.java:29359 )
L07| android.os.Handler.
     handleCallback( Handler.java:883 )
L08| android.os.Handler.
     dispatchMessage( Handler.java:100 )
L09| android.os.Looper.
     loop( Looper.java:237 )
L10| android.app.ActivityThread.
     main( ActivityThread.java:8167 )
L11| java.lang.reflect.Method.invoke( Native Method )
L12| com.android.internal.os.RuntimeInit$MethodAndArgsCaller.
     run( RuntimeInit.java:496 )
L13| com.android.internal.os.ZygoteInit.
     main( ZygoteInit.java:1100 )

```
**Additional comments:**

*NONE*

**Comment by maxieds** [comment]
@SHMAUS-Carter 
This bug report does not contain enough useful information to keep open. Please post new ones as you encounter them coming in. Thanks. --MDS
