### ISSUE TITLE
Moto G6 that I own needs to be debugger

### ISSUE THREAD

**Issue by stacky1956** [maxieds/ChameleonMiniLiveDebugger#32]

**Comment by maxieds** [comment]
@stacky1956 
I do not understand your question. Are you able to run the CMLD app on your phone, or did you hit a runtime error? Please provide more information about your issue.

FYI, I have a cheaper end Moto-G7 device that I have used for testing. It works fine there. Make sure you have applied all system upgrades and patches to move your device to the latest and greatest Android OS 10 (API 29+, ideally).
