### ISSUE TITLE
Crash Report (CMLD 1.3.4-free):  Neither user 10818 nor current process has android.permission.BLUETOOTH_ADMIN. [Android 10, SDK 29]

### ISSUE THREAD

**Issue by SHMAUS-Carter** [maxieds/ChameleonMiniLiveDebugger#34]
@maxieds:

**Crash data summary:**
* *CMLD Version*: v1.3.4-free (8176:96)
* *CMLD GitHub Commit*: 1cddba77e675 @ Tue Jan 12 18:18:04 2021 -0500
* *CMLD Build Date*: 2021-01-12-181925
* *Chameleon Type*: <UNKNOWN>
* *Serial Connection Type*: NULL
* *Chameleon Config*: NOT SET
* *Chameleon Logmode*: NOT SET
* *Chameleon Timeout*: NOT SET
* *Android Device*: beyond2q
* *Android Manufacturer*: samsung
* *Android Brand*: samsung
* *Android Product*: beyond2qltesq
* *Android Model*: SM-G975U
* *Android Hardware*: qcom
* *Android SDK*: 29
* *Android OS Release*: samsung/beyond2qltesq/beyond2q:10/QP1A.190711.020/G975USQU4ETH7:user/release-keys 10 (REL / G975USQS4ETK2)
* *Android Board*: msmnile
* *Android Type*: user

**Stack trace:**
```java**Exception Message:** Need BLUETOOTH ADMIN permission: Neither user 10818 nor current process has android.permission.BLUETOOTH_ADMIN.



Detailed Stack Trace:
java.lang.SecurityException: Need BLUETOOTH ADMIN permission: Neither user 10818 nor current process has android.permission.BLUETOOTH_ADMIN.
	at android.os.Parcel.
     createException( Parcel.java:2088 )
	at android.os.Parcel.
     readException( Parcel.java:2056 )
	at android.os.Parcel.
     readException( Parcel.java:2004 )
	at android.bluetooth.IBluetooth$Stub$Proxy.
     cancelDiscovery( IBluetooth.java:3575 )
	at android.bluetooth.BluetoothAdapter.
     cancelDiscovery( BluetoothAdapter.java:2684 )
	at com.maxieds.chameleonminilivedebugger.e.
     r( BluetoothGattConnector.java:2 )
	at com.maxieds.chameleonminilivedebugger.f.
     s( BluetoothSerialInterface.java:1 )
	at com.maxieds.chameleonminilivedebugger.n.
     d( ChameleonSettings.java:2 )
	at com.maxieds.chameleonminilivedebugger.c0$p.
     onClick( UITabUtils.java:5 )
	at android.view.View.
     performClick( View.java:7862 )
	at android.widget.TextView.
     performClick( TextView.java:15004 )
	at android.widget.CompoundButton.
     performClick( CompoundButton.java:152 )
	at android.view.View.
     performClickInternal( View.java:7831 )
	at android.view.View.access$3600( View.java:879 )
	at android.view.View$PerformClick.
     run( View.java:29359 )
	at android.os.Handler.
     handleCallback( Handler.java:883 )
	at android.os.Handler.
     dispatchMessage( Handler.java:100 )
	at android.os.Looper.
     loop( Looper.java:237 )
	at android.app.ActivityThread.
     main( ActivityThread.java:8167 )
	at java.lang.reflect.Method.invoke( Native Method )
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.
     run( RuntimeInit.java:496 )
	at com.android.internal.os.ZygoteInit.
     main( ZygoteInit.java:1100 )

```

**Additional comments:**
*NONE -- Please fill in more details about how you generated this error, like what actions you took before this screen is displayed. Did the error happen on launch of the application? Did you click a button or switch tabs? Any extra details about how the error happened are useful to fixing the issue in future releases.*

I tried checking the bluetooth box

**Comment by maxieds** [comment]
@SHMAUS-Carter 
This issue should be fixed with the latest **v1.3.6** release of the software. Please upgrade and write back if you still have the issue. Thanks. -- MDS
