### ISSUE TITLE
App Screenshots

### ISSUE THREAD

**Issue by maxieds** [maxieds/ChameleonMiniLiveDebugger#4]
Mostly to get GitHub to host the screenshots for the page instead of linking to the Play Store images, which tend to change with new releases, here are several screenshots of the running app and its output: 

### Live Logging Interface:
<img src="https://user-images.githubusercontent.com/22165688/34923450-fc88e840-f969-11e7-9362-ad49841fe5d4.png" width="250" />

### Tools Menu:
<img src="https://user-images.githubusercontent.com/22165688/34923371-34be690c-f969-11e7-90a7-e1d7c74476d6.png" width="250" />
<img src="https://user-images.githubusercontent.com/22165688/34923374-34df3880-f969-11e7-9244-89c155926170.png" width="250" />
<img src="https://user-images.githubusercontent.com/22165688/34926076-36b4fbb0-f97b-11e7-8fba-6545a15aa28a.png" width="250" />
<img src="https://user-images.githubusercontent.com/22165688/34923375-34e9fda6-f969-11e7-8537-874cb7e96c78.png" width="250" />

### Logging Tools Menu:
<img src="https://user-images.githubusercontent.com/22165688/34923372-34c7c2b8-f969-11e7-8b57-5a100ac012c9.png" width="250" />

### Export Tab:
<img src="https://user-images.githubusercontent.com/22165688/34923373-34d27ac8-f969-11e7-8ba3-245a3101911a.png" width="250" />

### Sample Output of the Logging Data to PlainText File:
<img src="https://user-images.githubusercontent.com/22165688/34923369-34a7ec90-f969-11e7-9fde-13e6ca988d02.png" width="250" />

**Comment by maxieds** [comment]
Anyone else have any useful screenshots and/or app usages to share?

**Comment by gtpy** [comment]
@maxieds I’ll test your app today or tomorrow. Then I’ll post some screenshots from usage.

**Comment by maxieds** [comment]
New Tools Menu shot with the working threshold slider:
<img src="https://user-images.githubusercontent.com/22165688/34929656-1b3b261c-f993-11e7-8448-1d590be1b429.png" width="250" />

**Comment by gtpy** [comment]
Here are some more screenshots of the usage from v0.2.8

**Overview - With loaded slot#1 (mf_ultralight):**
![overview](https://user-images.githubusercontent.com/13873777/35063582-cedd74d2-fbc7-11e7-81a5-0cfc5e3df6bf.png)

**Print actual version of ChameleonMini:**
![version](https://user-images.githubusercontent.com/13873777/35063665-0b4623ce-fbc8-11e7-9b29-d65ed693ecbf.png)

**Reader Mode - slot#4 - identify (mf_ultralight) command:**
![reader_mf_ultralight](https://user-images.githubusercontent.com/13873777/35063727-43856402-fbc8-11e7-9c2d-7074eb45285f.png)

**Reader Mode - slot#4 - identify (mf_classic_1k) command:**
![reader_mf_classic_1k](https://user-images.githubusercontent.com/13873777/35063766-5ce6b162-fbc8-11e7-87e3-228a1bcf86a2.png)

**Peripherals and Log Mode -> changed LBS (left button short) = UID_RANDOM:**
(only changed middle RND, cause it's a modified firmware which I am running - original FW will randomize full UID)
![lbutton_short_rand_uid 1](https://user-images.githubusercontent.com/13873777/35063838-8e262ae6-fbc8-11e7-81a5-a1b66a9808ef.png)

**Changed UID RANDOM#2:**
![lbutton_short_rand_uid 2](https://user-images.githubusercontent.com/13873777/35063865-a11b0856-fbc8-11e7-9ac7-629517799b61.png)

**Comment by maxieds** [comment]
Very cool. Do you have any interest in the themed flavors?

One other feature that might be useful would be to dump an actual mfu card
into a format that can be uploaded as a card image. Any idea how difficult
that would be?

On Jan 17, 2018 3:00 PM, "init0" <notifications@github.com> wrote:

Here are some more screenshots of the usage from v0.2.8

*Overview - With loaded slot#1 (mf_ultralight):*
[image: overview]
<https://user-images.githubusercontent.com/13873777/35063582-cedd74d2-fbc7-11e7-81a5-0cfc5e3df6bf.png>

*Print actual version of ChameleonMini:*
[image: version]
<https://user-images.githubusercontent.com/13873777/35063665-0b4623ce-fbc8-11e7-9b29-d65ed693ecbf.png>

*Reader Mode - slot#4 - identify (mf_ultralight) command:*
[image: reader_mf_ultralight]
<https://user-images.githubusercontent.com/13873777/35063727-43856402-fbc8-11e7-9c2d-7074eb45285f.png>

*Reader Mode - slot#4 - identify (mf_classic_1k) command:*
[image: reader_mf_classic_1k]
<https://user-images.githubusercontent.com/13873777/35063766-5ce6b162-fbc8-11e7-87e3-228a1bcf86a2.png>

*Peripherals and Log Mode -> changed LBS (left button short) = UID_RANDOM:*
(only changed middle RND, cause it's a modified firmware which I am running
- original FW will randomize full UID)
[image: lbutton_short_rand_uid 1]
<https://user-images.githubusercontent.com/13873777/35063838-8e262ae6-fbc8-11e7-81a5-a1b66a9808ef.png>

*Changed UID RANDOM#2:*
[image: lbutton_short_rand_uid 2]
<https://user-images.githubusercontent.com/13873777/35063865-a11b0856-fbc8-11e7-9ac7-629517799b61.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/maxieds/ChameleonMiniLiveDebugger/issues/4#issuecomment-358425830>,
or mute the thread

**Comment by gtpy** [comment]
Sorry there was a little error in my compiled FW
Now the new build works like charm and shows the UID and IDENTIFY correct in header
![own_compiled 2](https://user-images.githubusercontent.com/13873777/35096406-5d20f0b4-fc4c-11e7-87cc-801c019f213c.png)

**Comment by maxieds** [comment]
![Screenshot_20200908-235241](https://user-images.githubusercontent.com/22165688/92552400-9165b280-f22e-11ea-85ea-950b431f381d.png)

**Comment by maxieds** [comment]
![Screenshot_20190326-222957](https://user-images.githubusercontent.com/22165688/92555686-39cb4500-f236-11ea-9ccc-f6e2f84674c0.png)
![Screenshot_20190326-223012](https://user-images.githubusercontent.com/22165688/92555687-39cb4500-f236-11ea-8998-e2612f38178d.png)

**Comment by maxieds** [comment]
![Screenshot_20200909-012145](https://user-images.githubusercontent.com/22165688/92557820-18b92300-f23b-11ea-85e0-b2673428d8f8.png)

**Comment by maxieds** [comment]
Treating this long gone issue as an image upload thread for recent screenshots to be added soon to the WIKI...

![Screenshot_20201014-175141](https://user-images.githubusercontent.com/22165688/96054450-b366dc00-0e4f-11eb-9be0-068544ff624e.png)
![Screenshot_20201014-175153](https://user-images.githubusercontent.com/22165688/96054452-b366dc00-0e4f-11eb-83b2-37a5660c1d1d.png)
![Screenshot_20201014-175206](https://user-images.githubusercontent.com/22165688/96054453-b366dc00-0e4f-11eb-8550-ac50e336cbf3.png)
![Screenshot_20201014-175212](https://user-images.githubusercontent.com/22165688/96054454-b3ff7280-0e4f-11eb-945e-ef573ce6f7c1.png)
![Screenshot_20201014-175244](https://user-images.githubusercontent.com/22165688/96054455-b3ff7280-0e4f-11eb-969e-9d58e8d00c44.png)
![Screenshot_20201014-175255](https://user-images.githubusercontent.com/22165688/96054456-b3ff7280-0e4f-11eb-80be-c7775febacb4.png)
![Screenshot_20201014-175304](https://user-images.githubusercontent.com/22165688/96054460-b4980900-0e4f-11eb-8fae-835897ac6358.png)
![Screenshot_20201014-175313](https://user-images.githubusercontent.com/22165688/96054461-b4980900-0e4f-11eb-9aac-9dff4be82c41.png)
![Screenshot_20201014-175326](https://user-images.githubusercontent.com/22165688/96054463-b4980900-0e4f-11eb-905b-482de139bf05.png)
![Screenshot_20201014-175337](https://user-images.githubusercontent.com/22165688/96054464-b5309f80-0e4f-11eb-825b-4123e9ec43b3.png)
![Screenshot_20201014-175347](https://user-images.githubusercontent.com/22165688/96054465-b5309f80-0e4f-11eb-8d61-f5a652878701.png)
![Screenshot_20201014-175357](https://user-images.githubusercontent.com/22165688/96054467-b5309f80-0e4f-11eb-8d39-162f5f60f58e.png)
![Screenshot_20201014-175508](https://user-images.githubusercontent.com/22165688/96054468-b5309f80-0e4f-11eb-8513-0f8dfa4d577a.png)
![Screenshot_20201014-183434](https://user-images.githubusercontent.com/22165688/96054470-b5c93600-0e4f-11eb-93a6-5c7462419a33.png)
![Screenshot_20201014-183439](https://user-images.githubusercontent.com/22165688/96054471-b5c93600-0e4f-11eb-9e62-3dbd36d4df4d.png)
![Screenshot_20201014-183444](https://user-images.githubusercontent.com/22165688/96054472-b5c93600-0e4f-11eb-8e15-e969ac68d2a9.png)
![Screenshot_20201014-183454](https://user-images.githubusercontent.com/22165688/96054473-b661cc80-0e4f-11eb-81c3-cad1aaa62e21.png)
![Screenshot_20201014-183503](https://user-images.githubusercontent.com/22165688/96054474-b661cc80-0e4f-11eb-9f90-9772e2879ede.png)
![Screenshot_20201014-183513](https://user-images.githubusercontent.com/22165688/96054475-b661cc80-0e4f-11eb-852b-2b336819ce7a.png)
![Screenshot_20201014-183522](https://user-images.githubusercontent.com/22165688/96054476-b661cc80-0e4f-11eb-82b2-35bda246650f.png)
![Screenshot_20201014-183526](https://user-images.githubusercontent.com/22165688/96054477-b6fa6300-0e4f-11eb-8e4f-149df05968db.png)
![Screenshot_20201014-183534](https://user-images.githubusercontent.com/22165688/96054478-b6fa6300-0e4f-11eb-9c76-5197ba24ea87.png)
![Screenshot_20201014-183539](https://user-images.githubusercontent.com/22165688/96054479-b6fa6300-0e4f-11eb-83d7-b7dc15e3c107.png)
![Screenshot_20201014-183544](https://user-images.githubusercontent.com/22165688/96054481-b6fa6300-0e4f-11eb-885c-bf3c7f07eb96.png)
![Screenshot_20201014-183549](https://user-images.githubusercontent.com/22165688/96054482-b6fa6300-0e4f-11eb-8894-31bec41f1df5.png)
![Screenshot_20201014-183553](https://user-images.githubusercontent.com/22165688/96054483-b792f980-0e4f-11eb-85a5-91e8b3c53705.png)
![Screenshot_20201014-183843](https://user-images.githubusercontent.com/22165688/96054484-b792f980-0e4f-11eb-9760-739834b56c02.png)
![Screenshot_20201014-183853](https://user-images.githubusercontent.com/22165688/96054485-b792f980-0e4f-11eb-9548-480af8fe60e1.png)

**Comment by maxieds** [comment]
![Screenshot_20201014-175153-v2](https://user-images.githubusercontent.com/22165688/96055145-51a77180-0e51-11eb-9e7a-cb57724cac8a.png)

**Comment by maxieds** [comment]
![Screenshot_20201014-193415](https://user-images.githubusercontent.com/22165688/96056683-3c344680-0e55-11eb-8ee4-20ccd1e73e5e.png)
![Screenshot_20201014-193420](https://user-images.githubusercontent.com/22165688/96056684-3cccdd00-0e55-11eb-996f-7544f3418d17.png)
![Screenshot_20201014-194017](https://user-images.githubusercontent.com/22165688/96056686-3cccdd00-0e55-11eb-8b11-592184b6d70e.png)

**Comment by maxieds** [comment]
![Screenshot_20201014-194343](https://user-images.githubusercontent.com/22165688/96056871-a947dc00-0e55-11eb-80fc-9b3c1e6dda77.png)

**Comment by maxieds** [comment]
![Screenshot_20201014-175153](https://user-images.githubusercontent.com/22165688/96057285-984b9a80-0e56-11eb-86c6-62e8a4fcb2d6.png)

**Comment by maxieds** [comment]
![Uploading IMG_20201014_201222310.jpg…]()

**Comment by maxieds** [comment]
![Screenshot_20201020-143905](https://user-images.githubusercontent.com/22165688/96638748-9e29fb80-12ee-11eb-9a5f-9248ebdfffdf.png)
![Screenshot_20201020-143914](https://user-images.githubusercontent.com/22165688/96638749-9e29fb80-12ee-11eb-9070-4f06388a9eee.png)

**Comment by maxieds** [comment]
![Screenshot_20201020-195620](https://user-images.githubusercontent.com/22165688/96656898-c9bcde00-130e-11eb-9d3c-b708c633f31a.png)

**Comment by maxieds** [comment]
![Screen Shot 2020-11-18 at 2 49 26 PM](https://user-images.githubusercontent.com/22165688/99580712-c79d7c00-29ad-11eb-9508-bfe5534a85e1.png)

**Comment by maxieds** [comment]
![Screenshot_20210111-225226](https://user-images.githubusercontent.com/22165688/104268559-2dfcc300-5462-11eb-8010-d8ca5346481e.png)
![Screenshot_20210111-225232](https://user-images.githubusercontent.com/22165688/104268560-2dfcc300-5462-11eb-9b3e-0ef27f0b6c4f.png)
