### ISSUE TITLE
Crash Report (CMLD 1.3.4-free):  Neither user 10445 nor current process has android.permission.BLUETOOTH_ADMIN. [Android 10, SDK 29]

### ISSUE THREAD

**Issue by Kolplay** [maxieds/ChameleonMiniLiveDebugger#40]
@maxieds:

**Crash data summary:**
* *CMLD Version*: v1.3.4-free (8176:96)
* *CMLD GitHub Commit*: 1cddba77e675 @ Tue Jan 12 18:18:04 2021 -0500
* *CMLD Build Date*: 2021-01-12-181925
* *Chameleon Type*: <UNKNOWN>
* *Serial Connection Type*: NULL
* *Chameleon Config*: NOT SET
* *Chameleon Logmode*: NOT SET
* *Chameleon Timeout*: NOT SET
* *Android Device*: mdh50lm
* *Android Manufacturer*: LGE
* *Android Brand*: lge
* *Android Product*: mdh50lm
* *Android Model*: LM-Q730
* *Android Hardware*: mdh50lm
* *Android SDK*: 29
* *Android OS Release*: lge/mdh50lm/mdh50lm:10/QKQ1.200216.002/2025210286ad4:user/release-keys 10 (REL / 203560701aa8a)
* *Android Board*: mt6765
* *Android Type*: user

**Stack trace:**
```java**Exception Message:** Need BLUETOOTH ADMIN permission: Neither user 10445 nor current process has android.permission.BLUETOOTH_ADMIN.



Detailed Stack Trace:
java.lang.SecurityException: Need BLUETOOTH ADMIN permission: Neither user 10445 nor current process has android.permission.BLUETOOTH_ADMIN.
	at android.os.Parcel.
     createException( Parcel.java:2071 )
	at android.os.Parcel.
     readException( Parcel.java:2039 )
	at android.os.Parcel.
     readException( Parcel.java:1987 )
	at android.bluetooth.IBluetooth$Stub$Proxy.
     cancelDiscovery( IBluetooth.java:2473 )
	at android.bluetooth.BluetoothAdapter.
     cancelDiscovery( BluetoothAdapter.java:1909 )
	at com.maxieds.chameleonminilivedebugger.e.
     r( BluetoothGattConnector.java:2 )
	at com.maxieds.chameleonminilivedebugger.f.
     s( BluetoothSerialInterface.java:1 )
	at com.maxieds.chameleonminilivedebugger.n.
     d( ChameleonSettings.java:2 )
	at com.maxieds.chameleonminilivedebugger.c0$p.
     onClick( UITabUtils.java:5 )
	at android.view.View.
     performClick( View.java:7288 )
	at android.widget.CompoundButton.
     performClick( CompoundButton.java:142 )
	at android.view.View.
     performClickInternal( View.java:7258 )
	at android.view.View.access$4000( View.java:808 )
	at android.view.View$PerformClick.
     run( View.java:28019 )
	at android.os.Handler.
     handleCallback( Handler.java:883 )
	at android.os.Handler.
     dispatchMessage( Handler.java:100 )
	at android.os.Looper.
     loop( Looper.java:214 )
	at android.app.ActivityThread.
     main( ActivityThread.java:7615 )
	at java.lang.reflect.Method.invoke( Native Method )
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.
     run( RuntimeInit.java:492 )
	at com.android.internal.os.ZygoteInit.
     main( ZygoteInit.java:964 )

```

**Additional comments:**
*NONE -- Please fill in more details about how you generated this error, like what actions you took before this screen is displayed. Did the error happen on launch of the application? Did you click a button or switch tabs? Any extra details about how the error happened are useful to fixing the issue in" future releases.*

Just changing one of the options in the ap's settings, and when I clicked on the box so a check can appear, a trace report began to print.

**Comment by maxieds** [comment]
@Kolplay 
This issue should be fixed with the latest **v1.3.6** release of the software. Please upgrade and write back if you still have the issue. Thanks. -- MDS
