### ISSUE TITLE
Crash Report: CMLD 1.2.9-free running  20200606 [SDK 29] on device OUKITEL WP5_Pro WP5 Pro

### ISSUE THREAD

**Issue by Hackerass** [maxieds/ChameleonMiniLiveDebugger#43]
@maxieds:

**Crash data summary:**
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
* *[Ljava.lang.String;@a16d7f3*: [Ljava.lang.String;@a782cb0
**Stack trace:**
" + "```java
Could not find method actionButtonRestorePeripheralDefaults( View ) in a parent or ancestor Context for android:onClick attribute defined on view class androidx.appcompat.widget.f

L01| androidx.appcompat.app.h$a.
     a( AppCompatViewInflater.java:10 )
L02| androidx.appcompat.app.h$a.
     onClick( AppCompatViewInflater.java:2 )
L03| android.view.View.
     performClick( View.java:7146 )
L04| android.view.View.
     performClickInternal( View.java:7119 )
L05| android.view.View.access$3500( View.java:803 )
L06| android.view.View$PerformClick.
     run( View.java:27533 )
L07| android.os.Handler.
     handleCallback( Handler.java:883 )
L08| android.os.Handler.
     dispatchMessage( Handler.java:100 )
L09| android.os.Looper.
     loop( Looper.java:214 )
L10| android.app.ActivityThread.
     main( ActivityThread.java:7409 )
L11| java.lang.reflect.Method.invoke( Native Method )
L12| com.android.internal.os.RuntimeInit$MethodAndArgsCaller.
     run( RuntimeInit.java:492 )
L13| com.android.internal.os.ZygoteInit.
     main( ZygoteInit.java:980 )

```
**Additional comments:**

*NONE*

**Comment by maxieds** [comment]
@Hackerass 
You are using an out-of-date version of CMLD. Please upgrade and reopen the issue if it happens again in the latest release.
