### ISSUE TITLE
OnePlus 8t Smartphone

### ISSUE THREAD

**Issue by j3sk0** [maxieds/ChameleonMiniLiveDebugger#59]
**Exception Message:** Unable to start activity ComponentInfo{com.maxieds.chameleonminilivedebugger.paid/com.maxieds.chameleonminilivedebugger.LiveLoggerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPadding( int, int, int, int )' on a null object reference

Detailed Stack Trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxieds.chameleonminilivedebugger.paid/com.maxieds.chameleonminilivedebugger.LiveLoggerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPadding( int, int, int, int )' on a null object reference
	at android.app.ActivityThread.
     performLaunchActivity( ActivityThread.java:3622 )
	at android.app.ActivityThread.
     handleLaunchActivity( ActivityThread.java:3786 )
	at android.app.servertransaction.LaunchActivityItem.
     execute( LaunchActivityItem.java:85 )
	at android.app.servertransaction.TransactionExecutor.
     executeCallbacks( TransactionExecutor.java:135 )
	at android.app.servertransaction.TransactionExecutor.
     execute( TransactionExecutor.java:95 )
	at android.app.ActivityThread$H.
     handleMessage( ActivityThread.java:2257 )
	at android.os.Handler.
     dispatchMessage( Handler.java:106 )
	at android.os.Looper.
     loop( Looper.java:233 )
	at android.app.ActivityThread.
     main( ActivityThread.java:8030 )
	at java.lang.reflect.Method.invoke( Native Method )
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.
     run( RuntimeInit.java:631 )
	at com.android.internal.os.ZygoteInit.
     main( ZygoteInit.java:978 )
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPadding( int, int, int, int )' on a null object reference
	at com.maxieds.chameleonminilivedebugger.d0.
     h( Utils.java:3 )
	at com.maxieds.chameleonminilivedebugger.d0.
     i( Utils.java:1 )
	at com.maxieds.chameleonminilivedebugger.d0.
     j( Utils.java:1 )
	at com.maxieds.chameleonminilivedebugger.LiveLoggerActivity.
     onCreate( LiveLoggerActivity.java:45 )
	at android.app.Activity.
     performCreate( Activity.java:8006 )
	at android.app.Activity.
     performCreate( Activity.java:7990 )
	at android.app.Instrumentation.
     callActivityOnCreate( Instrumentation.java:1329 )
	at android.app.ActivityThread.
     performLaunchActivity( ActivityThread.java:3595 )
	... 11 more

i have paid for the version

**Comment by maxieds** [comment]
@j3sk0 
**This bug report is not helpful!** For example, you do not list the Android OS version nor the phone model, nor do you provide a brief synopsis of how the error came up (e.g., what did you do right before the crash?). The line numbers in the source will change with the build of the OS -- and that is specific to the phone vendor and which patches you have applied. 

How is this different from the issue in #58? The problem showed up on the newest, latest-and-greatest Android OS 12 platforms. A commit and a tester APK to resolve #58 was posted there this morning: [link to zipped signed APK](https://github.com/maxieds/ChameleonMiniLiveDebugger/files/8821556/ChameleonMiniLiveDebugger-v1.4.0-2022-06-02-031039-free-release.apk.zip). Have you tried to run it? Does it fix your crash?

This is [common sense](https://github.com/gtDMMB/RNAStructViz/wiki/BugReportingAndErrors). Spamming the issues page with useless information and complaints that are not reproducible is futile and annoying. 😦
