### ISSUE TITLE
Need better documentation for the app

### ISSUE THREAD

**Issue by maxieds** [maxieds/ChameleonMiniLiveDebugger#8]
Most of the functionality is pretty self-explanatory *if and only if* you are already very familiar with [this page](https://rawgit.com/emsec/ChameleonMini/master/Doc/Doxygen/html/_page__command_line.html) on the Chameleon command structure. Since the links to my app were posted on the Chameleon [Getting Started](https://rawgit.com/emsec/ChameleonMini/master/Doc/Doxygen/html/_page__getting_started.html) page, I've gotten a couple of confused emails about installation / how to compile too.  

Also, are there any other suggestions for other countries to try rollouts to on Play Store? I almost hesitate to ask this as much as I hesitate to go through and click the buttons to rollout to the 100+ choices available from the Play Store console (some cannot be selected due to US export restrictions hoewever)? Do you all think it's enough to just have it where it is now in the Play Store and link to the most recent APK's from the [releases page](https://github.com/maxieds/ChameleonMiniLiveDebugger/releases)?

**Comment by maxieds** [comment]
Here's a [start](https://github.com/maxieds/ChameleonMiniLiveDebugger/wiki/Documentation).

**Comment by gtpy** [comment]
If you need some support for documentation, you need to give me the authorization and I can help a bit.

**Comment by maxieds** [comment]
@gtpy: I just allowed public editing of the wiki for the time being. Please try to collaborate on [this page](https://github.com/maxieds/ChameleonMiniLiveDebugger/wiki/Documentation).

**Comment by maxieds** [comment]
I am going to give the [WIKI page](https://github.com/maxieds/ChameleonMiniLiveDebugger/wiki) an overhaul in the name of recent documentation that I have neglected properly so far. Please excuse any further posts to this thread for right now, as I need a place to easily upload images and screenshots to make this happen.

**Comment by maxieds** [comment]
![Screenshot_20200817-232042](https://user-images.githubusercontent.com/22165688/90468269-371c7a80-e0e4-11ea-8c48-0d73b89ccd6f.png)
![Screenshot_20200817-232048](https://user-images.githubusercontent.com/22165688/90468270-37b51100-e0e4-11ea-8c0b-1162dc2769c1.png)
![Screenshot_20200817-232054](https://user-images.githubusercontent.com/22165688/90468271-37b51100-e0e4-11ea-9bb9-e08141824d74.png)
![Screenshot_20200817-232108](https://user-images.githubusercontent.com/22165688/90468272-37b51100-e0e4-11ea-8a78-9676998d9249.png)
![Screenshot_20200817-232115](https://user-images.githubusercontent.com/22165688/90468274-37b51100-e0e4-11ea-9042-d61ce2406611.png)
![Screenshot_20200817-232120](https://user-images.githubusercontent.com/22165688/90468275-384da780-e0e4-11ea-8cd3-c52019c5b5a9.png)
![Screenshot_20200817-232126](https://user-images.githubusercontent.com/22165688/90468276-384da780-e0e4-11ea-9e4f-2f8370405ccf.png)
![Screenshot_20200817-232133](https://user-images.githubusercontent.com/22165688/90468277-384da780-e0e4-11ea-916f-5e633a225028.png)
![Screenshot_20200817-232138](https://user-images.githubusercontent.com/22165688/90468278-384da780-e0e4-11ea-81a0-72fae0a2da27.png)
![Screenshot_20200817-232224](https://user-images.githubusercontent.com/22165688/90468279-384da780-e0e4-11ea-9e93-fa0a93f7b968.png)
![Screenshot_20200817-232237](https://user-images.githubusercontent.com/22165688/90468280-38e63e00-e0e4-11ea-98e3-79920632921e.png)
![Screenshot_20200817-232242](https://user-images.githubusercontent.com/22165688/90468281-38e63e00-e0e4-11ea-8dd7-46c72ac034c2.png)
![Screenshot_20200817-232247](https://user-images.githubusercontent.com/22165688/90468282-38e63e00-e0e4-11ea-880b-6ce998ff7e86.png)
![Screenshot_20200817-232252](https://user-images.githubusercontent.com/22165688/90468283-397ed480-e0e4-11ea-8166-87fa228eb167.png)
![Screenshot_20200817-232258](https://user-images.githubusercontent.com/22165688/90468284-397ed480-e0e4-11ea-83e1-6ba77c87efd5.png)
![Screenshot_20200817-232306](https://user-images.githubusercontent.com/22165688/90468285-397ed480-e0e4-11ea-929c-c334b21b2784.png)
![Screenshot_20200817-232318](https://user-images.githubusercontent.com/22165688/90468287-397ed480-e0e4-11ea-93e4-2b75f09dc4ef.png)
![Screenshot_20200817-232337](https://user-images.githubusercontent.com/22165688/90468288-3a176b00-e0e4-11ea-84d4-e8f9256bbc0e.png)

**Comment by maxieds** [comment]
![unnamed](https://user-images.githubusercontent.com/22165688/90471230-a3e74300-e0eb-11ea-930a-444ace5fcaef.png)
